package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const hookStart = "# >>> CPAModelAdapter >>>"
const hookEnd = "# <<< CPAModelAdapter <<<"

func shQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'" }
func psQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func shellHook(binary string) string {
	b := shQuote(binary)
	return `# Generated by CPAModelAdapter. No API keys are stored in this file.
_cpa_refresh() {
    local cpa_value cpa_trace=0 cpa_result=0
    case $- in *x*) cpa_trace=1; set +x ;; esac
    if cpa_value="$(CPA_SHELL_INTEGRATED=1 ` + b + ` _key 2>/dev/null)"; then
        export CPA_API_KEY="$cpa_value"
    else
        unset CPA_API_KEY
        cpa_result=1
    fi
    unset cpa_value
    if [ "$cpa_trace" = 1 ]; then set -x; fi
    return "$cpa_result"
}
cpa() {
    local cpa_result=0
    CPA_SHELL_INTEGRATED=1 ` + b + ` "$@" || cpa_result=$?
    if [ "$cpa_result" = 0 ]; then
        case "${1-}" in
            init|add|use|delete|sync)
                if ! _cpa_refresh; then
                    printf '%s\n' 'CPA: 配置已更新，但环境刷新失败；请检查 cpa status。' >&2
                    cpa_result=1
                fi ;;
        esac
    fi
    return "$cpa_result"
}
_cpa_refresh || :
`
}

func powershellHook(binary string) string {
	return `# Generated by CPAModelAdapter. No API keys are stored in this file.
function global:Update-CPAEnvironment {
    $cpaOldMarker = $env:CPA_SHELL_INTEGRATED
    try {
        $env:CPA_SHELL_INTEGRATED = '1'
        $cpaValue = & ` + psQuote(binary) + ` _key 2>$null
        if ($LASTEXITCODE -eq 0) { $env:CPA_API_KEY = [string]$cpaValue }
    } finally {
        $cpaValue = $null
        $env:CPA_SHELL_INTEGRATED = $cpaOldMarker
    }
}
function global:cpa {
    $cpaOldMarker = $env:CPA_SHELL_INTEGRATED
    try {
        $env:CPA_SHELL_INTEGRATED = '1'
        & ` + psQuote(binary) + ` @args
        $cpaResult = $LASTEXITCODE
        if ($cpaResult -eq 0 -and $args.Count -gt 0 -and $args[0] -in @('init','add','use','delete','sync')) {
            Update-CPAEnvironment
            if ($LASTEXITCODE -ne 0) {
                Write-Warning 'CPA configuration saved, but environment refresh failed. Check cpa status.'
                $cpaResult = 1
            }
        }
        $global:LASTEXITCODE = $cpaResult
    } finally { $env:CPA_SHELL_INTEGRATED = $cpaOldMarker }
}
Update-CPAEnvironment
`
}

func appendHook(old []byte, hook string) ([]byte, error) {
	if !bytes.Contains(old, []byte(hookStart)) && bytes.Contains(old, []byte(hookEnd)) {
		return nil, errors.New("终端配置中的 CPA 标记不完整，拒绝覆盖")
	}
	nl := "\n"
	if bytes.Contains(old, []byte("\r\n")) {
		nl = "\r\n"
	}
	block := hookStart + nl + hook + nl + hookEnd + nl
	if start := bytes.Index(old, []byte(hookStart)); start >= 0 {
		endOffset := bytes.Index(old[start:], []byte(hookEnd))
		if endOffset < 0 {
			return nil, errors.New("终端配置中的 CPA 标记不完整，拒绝覆盖")
		}
		end := start + endOffset + len(hookEnd)
		if end < len(old) && old[end] == '\r' {
			end++
		}
		if end < len(old) && old[end] == '\n' {
			end++
		}
		if bytes.Contains(old[end:], []byte(hookStart)) {
			return nil, errors.New("发现重复 CPA 终端集成，请先检查重复标记")
		}
		return append(append(append([]byte{}, old[:start]...), []byte(block)...), old[end:]...), nil
	}
	return append(append(append([]byte{}, old...), []byte(nl)...), []byte(block)...), nil
}

func prependHook(old []byte, hook string) ([]byte, error) {
	updated, err := appendHook(old, hook)
	if err != nil {
		return nil, err
	}
	start := bytes.Index(updated, []byte(hookStart))
	end := start + bytes.Index(updated[start:], []byte(hookEnd)) + len(hookEnd)
	if end < len(updated) && updated[end] == '\r' {
		end++
	}
	if end < len(updated) && updated[end] == '\n' {
		end++
	}
	block := append([]byte{}, updated[start:end]...)
	rest := append(append([]byte{}, updated[:start]...), updated[end:]...)
	if !bytes.Contains(old, []byte(hookStart)) {
		rest = append([]byte{}, old...)
	}
	bom := []byte{0xef, 0xbb, 0xbf}
	if bytes.HasPrefix(rest, bom) {
		return append(append(append([]byte{}, bom...), block...), rest[len(bom):]...), nil
	}
	return append(block, rest...), nil
}

// Explicit installer entrypoint only. init/use never edit shell startup files.
func (a *App) setup() error {
	h, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	return a.setupAt(h)
}

func (a *App) setupAt(h string) error {
	var err error
	if err = ensurePrivateDir(a.dir); err != nil {
		return err
	}
	unlock, err := lockState(filepath.Join(a.dir, ".lock"))
	if err != nil {
		return err
	}
	defer unlock()
	if err = recoverTransaction(a.dir); err != nil {
		return err
	}
	source, err := os.Executable()
	if err != nil {
		return err
	}
	name := "cpa"
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	dest := filepath.Join(h, ".local", "bin", name)
	var targets []string
	var hookPath, hook string
	if runtime.GOOS == "windows" {
		hookPath = filepath.Join(a.dir, "shell.ps1")
		hook = powershellHook(dest)
		for _, command := range []string{"powershell.exe", "pwsh.exe"} {
			if exe, e := exec.LookPath(command); e == nil {
				out, e := exec.Command(exe, "-NoProfile", "-NonInteractive", "-Command", "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; $PROFILE.CurrentUserAllHosts").Output()
				if e != nil {
					return errors.New("无法确定 PowerShell profile 位置")
				}
				p := strings.TrimSpace(strings.TrimPrefix(string(out), "\ufeff"))
				if !filepath.IsAbs(p) || control(p) {
					return errors.New("PowerShell profile 路径无效")
				}
				if !includes(targets, p) {
					targets = append(targets, p)
				}
			}
		}
		if len(targets) == 0 {
			return errors.New("未找到 PowerShell；安装器不修改 cmd.exe 的全局 AutoRun")
		}
	} else {
		hookPath = filepath.Join(a.dir, "shell.sh")
		hook = shellHook(dest)
		targets = []string{filepath.Join(h, ".bashrc"), filepath.Join(h, ".zshrc"), filepath.Join(h, ".zshenv")}
		// Bash reads only the first existing login file; avoid creating a new
		// .bash_profile that would silently shadow an existing .profile.
		login := filepath.Join(h, ".profile")
		for _, p := range []string{".bash_profile", ".bash_login"} {
			if _, e := os.Stat(filepath.Join(h, p)); e == nil {
				login = filepath.Join(h, p)
				break
			}
		}
		targets = append(targets, login)
	}
	changes := []Change{{Path: hookPath, Data: []byte(hook)}}
	for _, p := range targets {
		old, e := os.ReadFile(p)
		if e != nil && !errors.Is(e, os.ErrNotExist) {
			return e
		}
		// Preserve UTF-8 and BOM. Never reinterpret UTF-16 PowerShell profiles.
		if bytes.IndexByte(old, 0) >= 0 {
			return errors.New("终端配置不是 UTF-8；请先转换编码，安装器不会覆盖")
		}
		line := ". " + shQuote(hookPath)
		if runtime.GOOS == "windows" {
			line = ". " + psQuote(hookPath)
		}
		newData, e := appendHook(old, line)
		if runtime.GOOS != "windows" && (filepath.Base(p) == ".bashrc" || filepath.Base(p) == ".zshenv") {
			newData, e = prependHook(old, line)
		}
		if e != nil {
			return e
		}
		if len(old) > 0 {
			backup := filepath.Join(a.dir, "backups", time.Now().UTC().Format("20060102T150405.000000000Z")+"-"+filepath.Base(p))
			if e = atomicWrite(backup, old); e != nil {
				return e
			}
		}
		changes = append(changes, Change{Path: p, Data: newData})
	}
	if filepath.Clean(source) != filepath.Clean(dest) {
		b, e := os.ReadFile(source)
		if e != nil {
			return e
		}
		if e = atomicWrite(dest, b); e != nil {
			return e
		}
		if runtime.GOOS != "windows" {
			if e = os.Chmod(dest, 0755); e != nil {
				return e
			}
		}
	}
	if err = commit(a.dir, changes); err != nil {
		return err
	}
	fmt.Fprintln(a.out, "已安装：", dest)
	fmt.Fprintln(a.out, "已配置 Bash/Zsh 或 PowerShell 的命令包装层；未迁移 Codex、未读取或保存任何新密钥。")
	fmt.Fprintln(a.out, "Bash 的 CPA 加载块位于非交互 return 之前，Zsh 同时配置 .zshenv；已运行的 SSH Codex 后端仍需重启。")
	fmt.Fprintln(a.out, "请重新打开终端，然后执行 cpa init。当前终端也可以加载：")
	if runtime.GOOS == "windows" {
		fmt.Fprintln(a.out, ". "+psQuote(hookPath))
	} else {
		fmt.Fprintln(a.out, ". "+shQuote(hookPath))
	}
	return nil
}
